service: botswana-fuel-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  timeout: 30

functions:
  getPrices:
    handler: handler.get_prices
    events:
      - httpApi:
          path: /prices
          method: get
          cors: true

plugins:
  - serverless-python-requirements